try {
   // Statements that might throw an exception
}
catch (exception) {
   // Handle the exception
}



//example


function findSum(numbers, startIndex, endIndex) {
   if (startIndex < 0) {
      throw "startIndex is less than 0.";
   } 
   else if (endIndex >= numbers.length) {
      throw "endIndex is too large.";  
   }

   let sum = 0;
   for (let i = startIndex; i <= endIndex; i++) {
      sum += numbers[i];
   }
   return sum;
}

let nums = [1, 2, 3, 4];
try {
   console.log(findSum(nums, 3, 4));
}
catch (exception) {
   console.log(exception);
}

console.log("Done!");

endIndex is too large.
Done!
false
false
true
let nums = [1, 2, 3, 4];

console.log(findSum(nums, 0, 2));

console.log(findSum(nums, 3, 4));

console.log("Done!");


